name: Secret Language Translator CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build website
      run: npm run build
      working-directory: website
      
    - name: Configure environment variables
      run: |
        echo "::set-env name=USERNAME::${{ secrets.USERNAME }}"
        echo "::set-env name=PASSWORD::${{ secrets.PASSWORD }}"
      
    - name: Deploy website
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: website/build
