name: Secret Language Translator CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create environment file
      run: echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV && echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
      
    - name: Deploy website
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: website
